# Generated by Django 5.2.10 on 2026-01-28 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchmaterial',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='researchmaterial',
            name='file_type',
            field=models.CharField(choices=[('image', 'Image'), ('audio', 'Audio'), ('video', 'Video'), ('pdf', 'Document')], max_length=50),
        ),
    ]
